### PR TITLE
Add gui

### PR DESCRIPTION
**Pull request by kylecorry31**
A GUI would be cool, so I made one. 

* All the sprites are custom built and made to look like the NES version of Bomberman, but I ain't an artist in any way
* Students will have to install pygame using pip as well
* The game is only playable through the command line, so the GUI is just for show

I'm from Group08 on Canvas

### CODE REVIEW

**Comment by ilpincy** [comment]
Oh wow, that's awesome and fast! Great addition! At the moment I can't make it work, I get an empty window as shown in the screenshot. What am I doing wrong?
screen shot 2019-02-09 at 07 08 42

**Comment by kylecorry31** [comment]
Hello, I'm not exactly sure what is wrong with that. What happens when you press enter again?

This is what it looks like on my computer:

screenshot from 2019-02-09 07-47-26

**Comment by kylecorry31** [comment]
Also, what happens if you run this:

`python3 -m pygame.examples.aliens`

It may be a mac specific issue, but I'll look into it.

**Comment by kylecorry31** [comment]
May be related to this unfortunately: https://github.com/pygame/pygame/issues/555

**Comment by ilpincy** [comment]
`python3 -m pygame.examples.aliens` works well (I don't have Mojave installed, still working on High Sierra).

I think I got it: you need to add a call to `pygame.event.clear()` (or manage events with `pygame.event.get()`) to prevent PyGame from thinking that the game crashed. When I added that line, it worked:

    def display_gui(self):
        pygame.event.clear()
        pygame.display.flip()
        ...

Thank you so much for doing this. I think I'll play with you code a little bit...

**Comment by kylecorry31** [comment]
Thanks for the fix! Interesting how it doesn't need that on Linux.

**Comment by ilpincy** [comment]
I refactored the code a little and fixed a little bug (the call to `display.flip()` was done in the wrong place). Thanks for this, it's really useful!

**Pull request closed without merging**
