### PR TITLE
 Fix x-direction movement bug

### PR DESCRIPTION
**Pull request by samgoldman**
There is a bug in the update_movable_entity method that allows any entity moving in the x-direction (it can also be moving in the y-direction) to move over walls. 
I fixed this by grouping the two statements checking for movement together separately from the check for a wall (before it would short-circuit after the x check, because the y check and the wall check were grouped together).

### CODE REVIEW

**Comment by ilpincy** [comment]
Very well spotted, thank you! What's your group number?

**Comment by samgoldman** [comment]
I'm in group 26.

**Comment by samgoldman** [comment]
@ilpincy I think I've encountered a related bug. Should entities be able to move over bombs?

**Comment by ilpincy** [comment]
Yes, they should!

**Comment by samgoldman** [comment]
Okay! In that case, when a character is on top of a bomb and it explodes, the character should die, right?

**Comment by ilpincy** [comment]
Ah shoot. I forgot to check the center of the blast. I'll fix that ^_^'

**Comment by ilpincy** [comment]
Done!

**Pull request merged**
